# 艺术模板 - 色彩、构图、音乐

COLOR_WHEEL_TEMPLATE = {
    "version": "1.0.0",
    "id": "art_color_wheel",
    "name": "色彩理论模拟",
    "description": "展示色轮、互补色、类似色等色彩关系",
    "canvas": {"width": 800, "height": 500, "backgroundColor": "#1a1a2e", "renderer": "pixi", "antialias": True},
    "assets": {"icons": [], "images": [], "sounds": [], "fonts": []},
    "elements": [
        {"id": "color_wheel_bg", "name": "色轮背景", "type": "shape", "transform": {"position": {"x": 300, "y": 250}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 0, "interactive": False, "shape": {"shapeType": "circle", "radius": 180, "fill": {"type": "solid", "color": "#2d2d44"}, "stroke": {"color": "#4a4a6a", "width": 2}}},
        {"id": "red", "name": "红色", "type": "shape", "transform": {"position": {"x": 300, "y": 100}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": True, "shape": {"shapeType": "circle", "radius": 35, "fill": {"type": "solid", "color": "#ef4444"}, "stroke": {"color": "#ffffff", "width": 3}}},
        {"id": "orange", "name": "橙色", "type": "shape", "transform": {"position": {"x": 430, "y": 150}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": True, "shape": {"shapeType": "circle", "radius": 35, "fill": {"type": "solid", "color": "#f97316"}, "stroke": {"color": "#ffffff", "width": 3}}},
        {"id": "yellow", "name": "黄色", "type": "shape", "transform": {"position": {"x": 430, "y": 300}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": True, "shape": {"shapeType": "circle", "radius": 35, "fill": {"type": "solid", "color": "#eab308"}, "stroke": {"color": "#ffffff", "width": 3}}},
        {"id": "green", "name": "绿色", "type": "shape", "transform": {"position": {"x": 300, "y": 400}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": True, "shape": {"shapeType": "circle", "radius": 35, "fill": {"type": "solid", "color": "#22c55e"}, "stroke": {"color": "#ffffff", "width": 3}}},
        {"id": "blue", "name": "蓝色", "type": "shape", "transform": {"position": {"x": 170, "y": 300}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": True, "shape": {"shapeType": "circle", "radius": 35, "fill": {"type": "solid", "color": "#3b82f6"}, "stroke": {"color": "#ffffff", "width": 3}}},
        {"id": "purple", "name": "紫色", "type": "shape", "transform": {"position": {"x": 170, "y": 150}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": True, "shape": {"shapeType": "circle", "radius": 35, "fill": {"type": "solid", "color": "#8b5cf6"}, "stroke": {"color": "#ffffff", "width": 3}}},
        {"id": "center", "name": "中心", "type": "shape", "transform": {"position": {"x": 300, "y": 250}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 6, "interactive": False, "shape": {"shapeType": "circle", "radius": 20, "fill": {"type": "solid", "color": "#ffffff"}}},
        {"id": "preview_panel", "name": "预览面板", "type": "shape", "transform": {"position": {"x": 650, "y": 200}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 10, "interactive": False, "shape": {"shapeType": "rectangle", "width": 200, "height": 250, "fill": {"type": "solid", "color": "#1e293b"}, "stroke": {"color": "#475569", "width": 1}, "cornerRadius": 12}},
        {"id": "color1_preview", "name": "颜色1预览", "type": "shape", "transform": {"position": {"x": 600, "y": 130}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 11, "interactive": False, "shape": {"shapeType": "rectangle", "width": 70, "height": 70, "fill": {"type": "solid", "color": "#ef4444"}, "cornerRadius": 8}},
        {"id": "color2_preview", "name": "颜色2预览", "type": "shape", "transform": {"position": {"x": 700, "y": 130}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 11, "interactive": False, "shape": {"shapeType": "rectangle", "width": 70, "height": 70, "fill": {"type": "solid", "color": "#22c55e"}, "cornerRadius": 8}},
        {"id": "harmony_label", "name": "和谐类型", "type": "text", "transform": {"position": {"x": 650, "y": 200}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 12, "interactive": False, "text": {"content": "互补色", "fontFamily": "Arial", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"}},
        {"id": "harmony_desc", "name": "和谐描述", "type": "text", "transform": {"position": {"x": 650, "y": 240}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 0.8, "zIndex": 12, "interactive": False, "text": {"content": "对比强烈\n视觉冲击力强", "fontFamily": "Arial", "fontSize": 12, "color": "#94a3b8", "align": "center"}},
        {"id": "title", "name": "标题", "type": "text", "transform": {"position": {"x": 400, "y": 30}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 20, "interactive": False, "text": {"content": "色彩理论 - 色轮与配色", "fontFamily": "Arial", "fontSize": 26, "fontWeight": "bold", "color": "#ffffff", "align": "center"}},
        {"id": "btn_complementary", "name": "互补色按钮", "type": "shape", "transform": {"position": {"x": 580, "y": 400}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 15, "interactive": True, "shape": {"shapeType": "rectangle", "width": 100, "height": 36, "fill": {"type": "solid", "color": "#ef4444"}, "cornerRadius": 18}},
        {"id": "btn_complementary_text", "name": "互补色文字", "type": "text", "transform": {"position": {"x": 580, "y": 400}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 16, "interactive": False, "text": {"content": "互补色", "fontFamily": "Arial", "fontSize": 12, "fontWeight": "bold", "color": "#ffffff", "align": "center"}},
        {"id": "btn_analogous", "name": "类似色按钮", "type": "shape", "transform": {"position": {"x": 700, "y": 400}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 15, "interactive": True, "shape": {"shapeType": "rectangle", "width": 100, "height": 36, "fill": {"type": "solid", "color": "#3b82f6"}, "cornerRadius": 18}},
        {"id": "btn_analogous_text", "name": "类似色文字", "type": "text", "transform": {"position": {"x": 700, "y": 400}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 16, "interactive": False, "text": {"content": "类似色", "fontFamily": "Arial", "fontSize": 12, "fontWeight": "bold", "color": "#ffffff", "align": "center"}},
        {"id": "btn_triadic", "name": "三角色按钮", "type": "shape", "transform": {"position": {"x": 640, "y": 450}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 15, "interactive": True, "shape": {"shapeType": "rectangle", "width": 100, "height": 36, "fill": {"type": "solid", "color": "#22c55e"}, "cornerRadius": 18}},
        {"id": "btn_triadic_text", "name": "三角色文字", "type": "text", "transform": {"position": {"x": 640, "y": 450}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 16, "interactive": False, "text": {"content": "三角配色", "fontFamily": "Arial", "fontSize": 12, "fontWeight": "bold", "color": "#ffffff", "align": "center"}}
    ],
    "timelines": [],
    "interactions": [
        {"id": "click_red", "name": "点击红色", "enabled": True, "trigger": {"type": "click", "targetId": "red"}, "actions": [{"type": "log", "params": {"message": "选择红色"}}]},
        {"id": "click_complementary", "name": "点击互补色", "enabled": True, "trigger": {"type": "click", "targetId": "btn_complementary"}, "actions": [{"type": "log", "params": {"message": "显示互补色"}}]},
        {"id": "click_analogous", "name": "点击类似色", "enabled": True, "trigger": {"type": "click", "targetId": "btn_analogous"}, "actions": [{"type": "log", "params": {"message": "显示类似色"}}]}
    ],
    "variables": [
        {"id": "selected_color", "name": "选中颜色", "type": "string", "defaultValue": "red"},
        {"id": "harmony_type", "name": "配色类型", "type": "string", "defaultValue": "complementary"}
    ],
    "metadata": {"author": "HERCU", "version": "1.0.0", "tags": ["艺术", "色彩", "配色"], "category": "art"}
}

COMPOSITION_TEMPLATE = {
    "version": "1.0.0",
    "id": "art_composition",
    "name": "构图原理模拟",
    "description": "展示三分法、黄金分割等构图原理",
    "canvas": {"width": 800, "height": 500, "backgroundColor": "#0f172a", "renderer": "pixi", "antialias": True},
    "assets": {"icons": [], "images": [], "sounds": [], "fonts": []},
    "elements": [
        {"id": "canvas_frame", "name": "画布框", "type": "shape", "transform": {"position": {"x": 350, "y": 250}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 0, "interactive": False, "shape": {"shapeType": "rectangle", "width": 480, "height": 360, "fill": {"type": "solid", "color": "#1e293b"}, "stroke": {"color": "#475569", "width": 2}, "cornerRadius": 4}},
        {"id": "grid_v1", "name": "竖线1", "type": "shape", "transform": {"position": {"x": 270, "y": 250}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 0.5, "zIndex": 2, "interactive": False, "shape": {"shapeType": "line", "points": [{"x": 0, "y": -180}, {"x": 0, "y": 180}], "stroke": {"color": "#f59e0b", "width": 2}}},
        {"id": "grid_v2", "name": "竖线2", "type": "shape", "transform": {"position": {"x": 430, "y": 250}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 0.5, "zIndex": 2, "interactive": False, "shape": {"shapeType": "line", "points": [{"x": 0, "y": -180}, {"x": 0, "y": 180}], "stroke": {"color": "#f59e0b", "width": 2}}},
        {"id": "grid_h1", "name": "横线1", "type": "shape", "transform": {"position": {"x": 350, "y": 190}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 0.5, "zIndex": 2, "interactive": False, "shape": {"shapeType": "line", "points": [{"x": -240, "y": 0}, {"x": 240, "y": 0}], "stroke": {"color": "#f59e0b", "width": 2}}},
        {"id": "grid_h2", "name": "横线2", "type": "shape", "transform": {"position": {"x": 350, "y": 310}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 0.5, "zIndex": 2, "interactive": False, "shape": {"shapeType": "line", "points": [{"x": -240, "y": 0}, {"x": 240, "y": 0}], "stroke": {"color": "#f59e0b", "width": 2}}},
        {"id": "point1", "name": "焦点1", "type": "shape", "transform": {"position": {"x": 270, "y": 190}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": False, "shape": {"shapeType": "circle", "radius": 10, "fill": {"type": "solid", "color": "#ef4444"}}},
        {"id": "point2", "name": "焦点2", "type": "shape", "transform": {"position": {"x": 430, "y": 190}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": False, "shape": {"shapeType": "circle", "radius": 10, "fill": {"type": "solid", "color": "#ef4444"}}},
        {"id": "point3", "name": "焦点3", "type": "shape", "transform": {"position": {"x": 270, "y": 310}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": False, "shape": {"shapeType": "circle", "radius": 10, "fill": {"type": "solid", "color": "#ef4444"}}},
        {"id": "point4", "name": "焦点4", "type": "shape", "transform": {"position": {"x": 430, "y": 310}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 5, "interactive": False, "shape": {"shapeType": "circle", "radius": 10, "fill": {"type": "solid", "color": "#ef4444"}}},
        {"id": "subject", "name": "主体", "type": "shape", "transform": {"position": {"x": 270, "y": 190}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 10, "interactive": True, "shape": {"shapeType": "circle", "radius": 40, "fill": {"type": "solid", "color": "#3b82f6"}, "stroke": {"color": "#ffffff", "width": 3}}},
        {"id": "title", "name": "标题", "type": "text", "transform": {"position": {"x": 400, "y": 30}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 20, "interactive": False, "text": {"content": "构图原理 - 三分法则", "fontFamily": "Arial", "fontSize": 26, "fontWeight": "bold", "color": "#ffffff", "align": "center"}},
        {"id": "info_panel", "name": "信息面板", "type": "shape", "transform": {"position": {"x": 700, "y": 250}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 0.9, "zIndex": 15, "interactive": False, "shape": {"shapeType": "rectangle", "width": 160, "height": 200, "fill": {"type": "solid", "color": "#1e293b"}, "stroke": {"color": "#475569", "width": 1}, "cornerRadius": 12}},
        {"id": "rule_name", "name": "规则名称", "type": "text", "transform": {"position": {"x": 700, "y": 180}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 16, "interactive": False, "text": {"content": "三分法则", "fontFamily": "Arial", "fontSize": 16, "fontWeight": "bold", "color": "#f59e0b", "align": "center"}},
        {"id": "rule_desc", "name": "规则描述", "type": "text", "transform": {"position": {"x": 700, "y": 230}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 0.8, "zIndex": 16, "interactive": False, "text": {"content": "将画面分成\n9个等分区域\n主体放在交点", "fontFamily": "Arial", "fontSize": 12, "color": "#94a3b8", "align": "center"}},
        {"id": "btn_thirds", "name": "三分法按钮", "type": "shape", "transform": {"position": {"x": 650, "y": 450}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 15, "interactive": True, "shape": {"shapeType": "rectangle", "width": 100, "height": 40, "fill": {"type": "solid", "color": "#f59e0b"}, "cornerRadius": 20}},
        {"id": "btn_thirds_text", "name": "三分法文字", "type": "text", "transform": {"position": {"x": 650, "y": 450}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 16, "interactive": False, "text": {"content": "三分法", "fontFamily": "Arial", "fontSize": 14, "fontWeight": "bold", "color": "#ffffff", "align": "center"}},
        {"id": "btn_golden", "name": "黄金分割按钮", "type": "shape", "transform": {"position": {"x": 770, "y": 450}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 15, "interactive": True, "shape": {"shapeType": "rectangle", "width": 100, "height": 40, "fill": {"type": "solid", "color": "#8b5cf6"}, "cornerRadius": 20}},
        {"id": "btn_golden_text", "name": "黄金分割文字", "type": "text", "transform": {"position": {"x": 770, "y": 450}, "rotation": 0, "scale": {"x": 1, "y": 1}, "anchor": {"x": 0.5, "y": 0.5}}, "visible": True, "opacity": 1, "zIndex": 16, "interactive": False, "text": {"content": "黄金分割", "fontFamily": "Arial", "fontSize": 14, "fontWeight": "bold", "color": "#ffffff", "align": "center"}}
    ],
    "timelines": [],
    "interactions": [
        {"id": "drag_subject", "name": "拖拽主体", "enabled": True, "trigger": {"type": "drag", "targetId": "subject"}, "actions": [{"type": "log", "params": {"message": "主体被拖拽"}}]},
        {"id": "click_thirds", "name": "点击三分法", "enabled": True, "trigger": {"type": "click", "targetId": "btn_thirds"}, "actions": [{"type": "log", "params": {"message": "显示三分法"}}]},
        {"id": "click_golden", "name": "点击黄金分割", "enabled": True, "trigger": {"type": "click", "targetId": "btn_golden"}, "actions": [{"type": "log", "params": {"message": "显示黄金分割"}}]}
    ],
    "variables": [
        {"id": "composition_type", "name": "构图类型", "type": "string", "defaultValue": "thirds"},
        {"id": "subject_position", "name": "主体位置", "type": "string", "defaultValue": "top_left"}
    ],
    "metadata": {"author": "HERCU", "version": "1.0.0", "tags": ["艺术", "构图", "摄影"], "category": "art"}
}
